### ISSUE TITLE
Make all defaults configurable

### ISSUE THREAD

**Issue by tkruse** [r-kells/scream#26]
Hi, just discovered scream project, looks nice.

What deters me most is that scream defaults cannot easily be configured. Being opinionated is good, but any user should feel safe to upgrade to new versions of scream without undue breakage, and that works best when all opinionated defaults are part of the generated source that is in version control. As an example, tox.init currently is generated from a template in tox.py, instead it could be generated from a `generated tox.ini.IN`, so that I can modify that file, and upgrading scream to a different version with a different tox.py will still give me the same reliable results.

So I would like to be able to configure all tox configuration, but also what blocked me was the packaging/naming conventions:
```
$ scream new xyz.foo_bar
Packages must not contain any of: '_'
```

Any such rule should be changeable in source to suit project needs.

**Comment by r-kells** [comment]
@tkruse thanks a ton for this feedback! I'm hoping to get back into the project soon and make it more generally applicable. More flexible config is definitely on that list.

Please check back soon, but until then feel free to steal some ideas for your own monorepo.

**Comment by r-kells** [comment]
@tkruse I have some rough ideas on your points. What I might do is make a branch and update the `README` with a description of how the templates / other defaults can be configurable.  Then hopefully I can get your feedback on the approach. 

I also have a good idea about how to remedy the `_` in package name issue. I baked that a bit too hard into the code to begin with, so its not a simple one-liner. I'll get to it though.

**Comment by tkruse** [comment]
It's not urgent for me. I might check again in a year or so. This ticket can be closed in any case, it was more of an email.
